/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewsProjetoTC;

// Importando todas as classes do pacote Models
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelsProjetoTC.Arquivo;
import modelsProjetoTC.Automato;
import modelsProjetoTC.Estado;
import modelsProjetoTC.Transicao;

/**
 *
 * @author Gabriel
 */
public class ViewInicial extends javax.swing.JFrame {
    
    // Tela Definicao de estados
    private static ViewDefinirTransacoes telaTransicoes;

    // Variaveis para serem usadas no andamento do programa.
    private static Automato auto;
    private static Arquivo criador;
    
    // ArrayLists
    private static ArrayList<Estado> listaEstados;
    private static Estado estado;
    private static ArrayList<Estado> listaEstadoFinal;
    private static ArrayList<Transicao> listTransicoes;
    
    /**
     * Creates new form viewInicial
     */
    public ViewInicial() {
        initComponents();
        // Setando titulo
        this.setTitle("Automato Não Deterministico");
        //Não maximiza
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnDefTrans = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtListEstados = new javax.swing.JTextField();
        txtEstadoInic = new javax.swing.JTextField();
        txtEstadosFins = new javax.swing.JTextField();
        txtAlfabetoAutom = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Lista de Estados:");

        jLabel3.setText("Estado Inicial:");

        jLabel4.setText("Estado(os) Final(is):");

        jLabel8.setText("Alfabeto do Automato:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Separar Estados por Virgula");

        btnDefTrans.setText("Definir Transições");
        btnDefTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefTransActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Epsilon = $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(btnDefTrans))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(53, 53, 53)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtListEstados)
                                .addComponent(txtEstadoInic, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEstadosFins)
                                .addComponent(txtAlfabetoAutom)))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtListEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEstadoInic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEstadosFins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAlfabetoAutom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(btnDefTrans)
                .addGap(28, 28, 28))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDefTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefTransActionPerformed
        // TODO add your handling code here:
        auto = new Automato();
        criador = new Arquivo();
        estado = new Estado();
        listaEstados = new ArrayList<>();
        listaEstadoFinal = new ArrayList<>();
        
        // Strings e Arrays.
        String[] listEstados;
        String[] listEstadosFinais;
        Estado estadoInicial = new Estado();
        
        // Resetando os atributos do automato
        auto.resetar();
        
        // Pegando os dados dos campos para a criação do automato.
        if(txtListEstados.getText().equals("") || txtEstadoInic.getText().equals("") || txtEstadosFins.getText().equals("") || txtAlfabetoAutom.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha os campos vazios!!");
        }else{
            // Pegando o campo de estados, quebrando e gerando um Array de String com o nome dos Estados.
            System.out.println("======= Tela INICIAL =======");
            System.out.println("LISTA ESTADOS ARRAY");
            listEstados = txtListEstados.getText().split(",");
            for(int i=0; i<listEstados.length; i++){
                System.out.println(listEstados[i]);
//                listaEstados.add(new Estado(i, listEstados[i]));
//                System.out.println(listaEstados.get(i).nome);
            }
            System.out.println("LISTA ESTADOS ADICIONADOS ARRAYLIST");
            for(int i=0; i<listEstados.length; i++){
//                System.out.println(listEstados[i]);
                listaEstados.add(new Estado(i, listEstados[i]));
                System.out.println(listaEstados.get(i).nome);
            }
            System.out.println("QUANTIDADE LISTA ESTADOS ARRAY: " + listEstados.length);
            System.out.println("QUANTIDADE LISTA ESTADOS ARRAYLIST: " + listaEstados.size());
            // Campo estado Inicial.
            
            estadoInicial.setNome(txtEstadoInic.getText());
            System.out.println("LISTA ESTADOS FINAIS ARRAY");
            // Seguindo a mesma logica do campo dos estados, porém para os estados finais.
            listEstadosFinais = txtEstadosFins.getText().split(",");
            for(int i=0; i<listEstadosFinais.length; i++){
                System.out.println(listEstadosFinais[i]);
                //listaEstadoFinal.add(new Estado(i, listEstadosFinais[i]));
            }
            System.out.println("LISTA ESTADOS FINAIS ADICIONADOS ARRAYLIST");
            for(int i=0; i<listEstadosFinais.length; i++){
//                System.out.println(listEstadosFinais[i]);
                listaEstadoFinal.add(new Estado(i, listEstadosFinais[i]));
                System.out.println(listaEstadoFinal.get(i).nome);
            }
            System.out.println("QUANTIDADE LISTA ESTADOS FINAIS ARRAYLIST: " + listaEstadoFinal.size());
            System.out.println("QUANTIDADE LISTA ESTADOS FINAIS ARRAY: " + listEstadosFinais.length);
        }
        
        ViewDefinirTransacoes telaTransacoes = new ViewDefinirTransacoes(listaEstados, estadoInicial, listaEstadoFinal);
        telaTransacoes.setVisible(true);
    }//GEN-LAST:event_btnDefTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDefTrans;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAlfabetoAutom;
    private javax.swing.JTextField txtEstadoInic;
    private javax.swing.JTextField txtEstadosFins;
    private javax.swing.JTextField txtListEstados;
    // End of variables declaration//GEN-END:variables
}
