/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewsProjetoTC;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelsProjetoTC.Estado;

/**
 *
 * @author Gabriel
 */
public class ViewCheckEstados extends javax.swing.JFrame {
    
    // ArrayLists para alimentar a view
    private static ArrayList<Estado> listaEstados;
    private static Estado estado;
    private static ArrayList<Estado> listaEstadosFinal;
    private static ArrayList<Character> alfabeto;

    /**
     * Creates new form viewCheckEstados
     * @param listEstados
     * @param alfabeto
     */
    public ViewCheckEstados(ArrayList<Estado> listEstados, ArrayList<Character> alfabeto) {
        initComponents();
        this.setResizable(false);
        this.setTitle("Definir Estados");
        this.listaEstados = listEstados;
        this.alfabeto = alfabeto;
        
        // Preenchendo a table.
        for(int i=0; i<listaEstados.size(); i++){
            // Montando a linha utilizando DefaultTableModel para a Jtable.
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String[] linhaDados = new String[] {listaEstados.get(i).getNome()};
            model.addRow(linhaDados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCheckEstados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextEstadoIni = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estados", "Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        btnCheckEstados.setText("Definir Transições");
        btnCheckEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckEstadosActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado Inicial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEstadoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCheckEstados)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextEstadoIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCheckEstados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckEstadosActionPerformed
        // Inicializando os itens que guadarao as informações.
        listaEstadosFinal = new ArrayList<>();
        estado = new Estado();
        
        // Pegando o estado Inicial
        if(jTextEstadoIni.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo com o estado inicial!");
            return;
        }
        else {
            if(Estado.retornaEstado(listaEstados, jTextEstadoIni.getText()) == null){
                JOptionPane.showMessageDialog(null, "Preencha o campo com um Estado valido!");
                return;
            }
            else {
                // Pegando estado Inicial
                Estado estadoIni = Estado.retornaEstado(listaEstados, jTextEstadoIni.getText());
            }
        }
        
        // Pegando os selects
        int x=0;
        Object[] vetorObjetos = pegarColunaJTable(jTable1, 1);
        for (Object item : vetorObjetos) {
            if(item != null && ((boolean) item))
                listaEstadosFinal.add(Estado.retornaEstado(listaEstados, (String) jTable1.getValueAt(x, 0)));
            
        x++;
        }
        
        new ViewDefinirTransacoes(listaEstados, estado, listaEstadosFinal, alfabeto).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCheckEstadosActionPerformed

    // Pegando a coluna da jTable e salvando em um array de objetos.
    public static Object[] pegarColunaJTable(JTable jtable, int coluna){
        int linhas = jtable.getRowCount();
        Object[] dados = new Object[linhas];
        for(int i=0; i<linhas; i++)
            dados[i] = jtable.getValueAt(i, coluna);
        
        return dados;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCheckEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCheckEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCheckEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCheckEstados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCheckEstados(listaEstados, alfabeto).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckEstados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextEstadoIni;
    // End of variables declaration//GEN-END:variables
}
